[package]
name = "kutyus_network"
version = "0.1.0"
authors = ["Marton Suranyi <marton.suranyi@gmail.com>"]

[dependencies]
error-chain = "0.11.0"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
